# Exploration of Watershed Boundary (HUC-8) Dataset

In [1]:
%pip install geopandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopandas in /home/creighton.jo/.local/lib/python3.12/site-packages (1.2.0)
Requirement already satisfied: numpy>=2 in /shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages (from geopandas) (2.4.4)
Requirement already satisfied: packaging in /shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=2.2.0 in /shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages (from geopandas) (2.3.3)
Requirement already satisfied: pyogrio>=0.8 in /home/creighton.jo/.local/lib/python3.12/site-packages (from geopandas) (0.13.0)
Requirement already satisfied: pyproj>=3.7.0 in /home/creighton.jo/.local/lib/python3.12/site-packages (from geopandas) (3.8.0)
Requirement already satisfied: shapely>=2.1.0 in /home/creighton.jo/.local/lib/python3.12/site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages (from pandas>=2.2.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages (from pandas>=2.2.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages (from pandas>=2.2.0->geopandas) (2023.3)
Requirement already satisfied: certifi in /shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages (from pyogrio>=0.8->geopandas) (2024.6.2)
Requirement already satisfied: six>=1.5 in /shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->geopandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import geopandas as gpd #TODO - set up conda environment to install all project pkgs and prevent these errors
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3259918/2784260871.py", line 1, in <module>
    import geopandas as gpd #TODO - set up conda environment to install all project pkgs and prevent these errors
  File "/home/creighton.jo/.local/lib/python3.12/site-packages/geopandas/__init__.py", line 3, in <module>
    from geopandas.geoseries import GeoSeries
  File "/home/creighton.jo/.local/lib/python3.12/site-packages/geopandas/geoseries.py", line 8, in <module>
    import pandas as pd
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py", line 53, in <module>
    from pandas.core import (
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3259918/2784260871.py", line 1, in <module>
    import geopandas as gpd #TODO - set up conda environment to install all project pkgs and prevent these errors
  File "/home/creighton.jo/.local/lib/python3.12/site-packages/geopandas/__init__.py", line 3, in <module>
    from geopandas.geoseries import GeoSeries
  File "/home/creighton.jo/.local/lib/python3.12/site-packages/geopandas/geoseries.py", line 8, in <module>
    import pandas as pd
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py", line 67, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/arrays/masked.py", line 61, in <module>
    from pandas.core import (
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/shared/EL9/explorer/anaconda3/2024.06/lib/python3.12/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

## Initial Investigation

In [3]:
gpkg_path = "../data/raw/wbd/WBD_National_GPKG.gpkg"
wbd_df = gpd.read_file(gpkg_path,layer="WBDHU8")
wbd_df.head()

,tnmid,metasourceid,sourcedatadesc,sourceoriginator,sourcefeatureid,loaddate,referencegnis_ids,areaacres,areasqkm,states,huc8,name,globalid,shape_Length,shape_Area,geometry
0,{DA87EC7E-FB57-4A0E-8713-10567559A58B},{511D2AC8-11BA-45FC-AB98-F69D693D4C44},Watershed Boundary Dataset (WBD),Natural Resources and Conservation Service and...,None,2024-08-16 10:24:20+00:00,626170,851585.17,3446.25,MI,04080204,Flint,{510E22D6-AB4D-4CDD-99CF-5CD58FEC5B94},4.645777,0.380858,"MULTIPOLYGON (((-83.24547 43.35439, -83.24507 ..."
1,{34237FD4-D8C2-47F4-8989-29AC92CA256D},{511D2AC8-11BA-45FC-AB98-F69D693D4C44},Watershed Boundary Dataset (WBD),Natural Resources and Conservation Service and...,None,2024-08-16 10:24:20+00:00,1867316,510065.30,2064.16,MI,04090003,Clinton,{A207672D-3D88-4E02-A497-D0CF75350200},3.381461,0.226767,"MULTIPOLYGON (((-83.01797 42.94371, -83.01772 ..."
2,{9518B2C0-766D-44A0-A156-DCA8E4551527},{511D2AC8-11BA-45FC-AB98-F69D693D4C44},Watershed Boundary Dataset (WBD),Natural Resources and Conservation Service and...,None,2024-08-16 10:24:20+00:00,1562290,673271.29,2724.63,"MI,WI",04030106,Brule,{AC5B9190-DEC8-4111-AF08-6C5993737A75},5.047323,0.317390,"MULTIPOLYGON (((-88.54782 46.53939, -88.54764 ..."
3,{2983B57A-C017-4813-9063-51B4213FF9AB},{511D2AC8-11BA-45FC-AB98-F69D693D4C44},Watershed Boundary Dataset (WBD),Natural Resources and Conservation Service and...,None,2024-08-16 10:24:20+00:00,248771,3206053.92,12974.45,"CA,MX",18100204,Salton Sea,{52127BF8-0115-49EC-BD9A-C06290D20546},8.257299,1.251929,"MULTIPOLYGON (((-115.92055 33.81369, -115.9204..."
4,{EF9CDE22-5978-45F7-95A8-36E84D408C08},{511D2AC8-11BA-45FC-AB98-F69D693D4C44},Watershed Boundary Dataset (WBD),Natural Resources and Conservation Service and...,None,2024-08-16 10:24:20+00:00,1621113,888549.87,3595.84,"MI,WI",04020102,Ontonagon,{29BE3289-DDD4-4B1D-98FB-33A3D2DBD493},5.163753,0.421148,"MULTIPOLYGON (((-89.32617 46.87654, -89.32562 ..."

In [4]:
wbd_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 2456 entries, 0 to 2455
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tnmid              2456 non-null   object
 1   metasourceid       2429 non-null   object
 2   sourcedatadesc     2395 non-null   object
 3   sourceoriginator   2426 non-null   object
 4   sourcefeatureid    0 non-null      object
 5   loaddate           2455 non-null   datetime64[ms, UTC]
 6   referencegnis_ids  2349 non-null   object
 7   areaacres          2449 non-null   float64
 8   areasqkm           2445 non-null   float64
 9   states             2456 non-null   object
 10  huc8               2456 non-null   object
 11  name               2456 non-null   object
 12  globalid           2456 non-null   object
 13  shape_Length       2456 non-null   float64
 14  shape_Area         2456 non-null   float64
 15  geometry           2456 non-null   geometry
dtypes: datetime64[ms, UTC](1), float64(4), geometry(1), object(10)
memory usage: 307.1+ KB

In [5]:
wbd_df.describe()

          areaacres      areasqkm  shape_Length   shape_Area
count  2.449000e+03   2445.000000   2456.000000  2456.000000
mean   1.135573e+06   4599.513450      5.386664     0.553176
std    1.164492e+06   4715.222603      3.514385     0.688240
min    2.440708e+04     98.770000      0.334411     0.008869
25%    5.721887e+05   2315.590000      3.507093     0.243869
50%    8.653398e+05   3504.010000      4.595288     0.370417
75%    1.319159e+06   5346.780000      6.072477     0.581599
max    2.099013e+07  84944.110000     50.484566    10.561233

In [6]:
# Check for duplicate names
duplicates = wbd_df[wbd_df["name"].duplicated(keep=False)].sort_values("name")
print(f"The HUC8 dataset contains {len(duplicates)} watersheds with the same name")
duplicates[["name", "huc8", "states"]].head(30)

The HUC8 dataset contains 241 watersheds with the same name

              name      huc8    states
185   Bayou Pierre  11140206     LA,TX
1223  Bayou Pierre  08060203     LA,MS
1738          Bear  11040005     CO,KS
758           Bear  06030006     AL,MS
425         Beaver  10130104        ND
1393        Beaver  10050014        MT
1433        Beaver  10110204     MT,ND
1273        Beaver  10190013        CO
582         Beaver  10250014     KS,NE
130         Beaver  10120107     SD,WY
650         Beaver  05030104        PA
1256           Big  10260007        KS
974            Big  08020304        AR
1906           Big  07140104        MO
1839     Big Muddy  07140106        IL
138      Big Muddy  10060006  CN,MT,ND
1283     Big Sandy  11020011        CO
1065     Big Sandy  15030201        AZ
1514     Big Sandy  05070204     KY,WV
1375     Big Sandy  10050005        MT
301      Big Sandy  14040104        WY
1096         Black  15060101        AZ
1113         Black  07040007        WI
1332         Black  03040205        SC
331          Black  04140301        NY
170          Black  08040305        LA
162          Black  03030006        NC
1534         Black  04070005        MI
1217         Black  03170007        MS
1689     Blackfoot  17040207        ID

Given that there are multiple watersheds with the same name, joining the dam removals based on name can get messy. Instead, a spatial join will be performed below; dams will be joined to the watersheds based on whether or not their coordinates are within a watershed polygon.

## Join to dam removal dataset

In [7]:
dam_df = pd.read_csv('../data/raw/dams/ARDamRemovalList_Figshare_Mar2026.csv')
merged = dam_df.merge(
    wbd_df,
    left_on="HUC8",
    right_on="name",
    how="left"
)

print(f"The joined table has {merged.shape[0]} rows and {merged.shape[1]} columns")
print(f"There are {len(merged["HUC8"].dropna().unique())} unique HUC8s")

The joined table has 2596 rows and 38 columns
There are 678 unique HUC8s

In [8]:
print(dam_df.shape)

(2325, 22)

In [9]:
# Convert dams to GeoDataFrame
dam_gdf = gpd.GeoDataFrame(
    dam_df,
    geometry=gpd.points_from_xy(
        dam_df["Longitude"],
        dam_df["Latitude"]
    ),
    crs="EPSG:4326"
)

# Make sure WBD uses the same CRS (coordinate system)
wbd_huc8 = wbd_df.to_crs(dam_gdf.crs)

# Spatial join
merged_df = gpd.sjoin(
    dam_gdf,
    wbd_huc8[["huc8", "name", "geometry"]],
    how="left",
    predicate="within"
)

print(merged_df.shape)

merged_df.head(20)

(2325, 26)

,AR_ID,NABI_ID,NID_ID,Dam_Name,Year_Removed,Latitude,Longitude,City_County,River,HUC8,...,Type_Material,Reason_for_removal,Miles_Restored_US,Miles_Restored_DS,River_Miles_Reported,Last_Updated,geometry,index_right,huc8,name
0,AK-001,AK91779,NaN,Lake Bettinger Complex Dam,NaN,57.803330,-152.395000,Kodiak,NaN,Kodiak-Afognak Islands,...,Timber,Delapidated,NaN,NaN,NaN,2/10/2026,POINT (-152.395 57.80333),1323.0,19020701,Kodiak-Afognak Islands
1,AK-002,AK91780,NaN,Bettinger Lower Reservoir Dam B,NaN,57.801670,-152.395000,Kodiak,NaN,Kodiak-Afognak Islands,...,Timber,Safety,NaN,NaN,NaN,2/10/2026,POINT (-152.395 57.80167),1323.0,19020701,Kodiak-Afognak Islands
2,AK-003,AK91781,NaN,Memory Estates Dam #1,NaN,62.618330,-149.427000,Matanuska-Susitna,NaN,Talkeetna River,...,Earthen,NaN,NaN,NaN,NaN,2/10/2026,POINT (-149.427 62.61833),2228.0,19020503,Talkeetna River
3,AK-004,AK91782,NaN,Memory Estates Dam #2,NaN,62.626670,-149.380000,Matanuska-Susitna,NaN,Talkeetna River,...,Earthen,NaN,NaN,NaN,NaN,2/10/2026,POINT (-149.38 62.62667),2228.0,19020503,Talkeetna River
4,AK-005,NaN,NaN,Switzer One Dam,1988,NaN,NaN,"Tongass National Forest, Juneau",Switzer Creek,Lynn Canal,...,NaN,Safety,NaN,NaN,NaN,11/10/2017,POINT (NaN NaN),NaN,NaN,NaN
5,AK-006,AK91783,NaN,Switzer Two Dam,1988,58.365000,-134.500000,"Tongass National Forest, Juneau",Switzer Creek,Lynn Canal,...,NaN,Safety,NaN,NaN,NaN,2/10/2026,POINT (-134.5 58.365),213.0,19010301,Lynn Canal
6,AK-007,AK45539,NaN,City of Kake Dam,2000,56.981540,-133.931000,Kake,Gunnuk Creek,Kuiu-Kupreanof-Mitkof Islands,...,NaN,Safety,NaN,NaN,NaN,2/10/2026,POINT (-133.931 56.98154),2287.0,19010210,Kuiu-Kupreanof-Mitkof Islands
7,AK-008,AK91784,NaN,Davidson Ditch Diversion Dam,2002,65.292800,-146.404000,Fairbanks North Star,Chatanika River,Tolovana River,...,NaN,Safety/Ecology,NaN,NaN,65,2/10/2026,POINT (-146.404 65.2928),2208.0,19080309,Tolovana River
8,AK-009,NaN,NaN,Unnamed (Bridle Path Dam),2004,NaN,NaN,NaN,Allison Creek,NaN,...,Concrete,Ecology,NaN,NaN,NaN,2/4/2022,POINT (NaN NaN),NaN,NaN,NaN
9,AK-010,AK91785,AK00093,Lower Eklutna River Dam,2017,61.449393,-149.323880,Anchorage,Eklutna,Anchorage,...,Concrete,Ecology,NaN,NaN,16,2/10/2026,POINT (-149.32388 61.44939),1157.0,19020401,Anchorage
10,AL-001,AL17574,NaN,Marvel Slab Dam,2004,33.165640,-87.029400,Montevallo,Cahaba River,Cahaba,...,Concrete,Ecology/Safety,NaN,NaN,NaN,2/10/2026,POINT (-87.0294 33.16564),1337.0,03150202,Cahaba
11,AL-002,NaN,NaN,Unnamed Dam,2007,NaN,NaN,NaN,Mud Creek,NaN,...,NaN,Ecology,NaN,NaN,NaN,2/4/2022,POINT (NaN NaN),NaN,NaN,NaN
12,AL-003,AL17575,NaN,Unnamed Dam,2010,32.363980,-85.121600,Seale,Uchee Creek,Middle Chattahoochee-Walter F,...,NaN,Ecology,NaN,NaN,25,2/10/2026,POINT (-85.1216 32.36398),761.0,03130003,Middle Chattahoochee-Walter F
13,AL-004,AL17573,NaN,Shades Branch Steel Ford,2011,33.220960,-87.029500,West Blocton,Shades Branch,Cahaba,...,NaN,Ecology,NaN,NaN,3,2/10/2026,POINT (-87.0295 33.22096),1337.0,03150202,Cahaba
14,AL-005,AL3891,NaN,Goodwins Mill Dam,2013,33.819730,-86.385500,St Clair County,Big Canoe Creek,Middle Coosa,...,Stone,Ecology,NaN,NaN,12,2/10/2026,POINT (-86.3855 33.81973),234.0,03150106,Middle Coosa
15,AL-006,AL17572,NaN,Old Shadow Lake Dam,2013,33.682780,-86.646400,Pinson,Turkey Creek,Locust,...,Concrete,Ecology/Safety,NaN,NaN,0.5,2/10/2026,POINT (-86.6464 33.68278),754.0,03160111,Locust
16,AL-007,AL550354,NaN,Howle and Turner Dam,2019,33.552030,-85.612050,Delta/Cleburne,Tallapoosa River,Upper Tallapoosa,...,NaN,Ecology/Safety,397,NaN,NaN,2/10/2026,POINT (-85.61205 33.55203),762.0,03150108,Upper Tallapoosa
17,AL-008,AL26339,NaN,Livingston Dam,2019,32.588457,-88.197545,Livingston,Sucarnoochee River,Mobile,...,Concrete/Steel,Obsolete/Ecology,NaN,NaN,NaN,2/10/2026,POINT (-88.19754 32.58846),1610.0,03160202,Sucarnoochee
18,AL-009,AL17578,NaN,Big Wills Creek Dam,2022,34.005873,-86.068766,Etowah,Big Wills Creek,Middle Coosa,...,NaN,NaN,45.7,NaN,NaN,2/10/2026,POINT (-86.06877 34.00587),234.0,03150106,Middle Coosa
19,AR-001,NaN,NaN,Winton Springs Dam,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11/10/2017,POINT (NaN NaN),NaN,NaN,NaN

In [10]:
print(f"There are {len(merged_df['AR_ID'].dropna().unique())} unique dams") # should be 2325

There are 2325 unique dams

## Extract HUC4 codes from HUC8 codes in joined dataset to get all relevant HUC4 watersheds

This is done so that only a subset of all streams in the US are downloaded - we do not want to download the entire stream dataset as this would be ginormous

In [11]:
huc4s = merged_df['huc8'].str[:4].dropna().unique()
print(huc4s)

['1902' '1901' '1908' '0315' '0313' '0316' '0802' '1101' '1114' '1506'
 '1501' '1505' '1801' '1805' '1802' '1804' '1806' '1807' '1019' '1402'
 '1102' '1401' '0110' '0108' '0204' '0314' '0310' '0305' '0306' '0307'
 '0312' '2006' '2001' '2007' '2002' '0706' '1017' '0710' '0708' '1704'
 '1701' '1706' '1601' '1705' '0709' '0714' '0514' '0713' '0712' '0512'
 '0410' '0405' '0508' '1107' '0510' '0511' '0513' '1201' '0109' '0202'
 '0107' '0205' '0207' '0206' '0105' '0102' '0106' '0103' '0104' '0101'
 '0407' '0406' '0402' '0401' '0408' '0403' '0424' '0409' '0420' '0419'
 '0703' '0701' '0704' '0702' '0902' '1030' '1004' '1003' '1010' '1009'
 '1005' '1007' '1002' '0604' '0601' '0801' '0602' '0302' '0304' '0303'
 '0505' '1013' '1016' '1011' '0901' '1025' '1014' '0203' '1306' '1302'
 '1808' '1606' '1604' '0414' '0430' '0429' '0412' '0413' '0411' '0504'
 '0503' '0506' '0509' '1105' '1709' '1707' '1710' '1708' '1712' '0501'
 '0502' '2101' '1012' '1015' '0603' '1206' '1207' '1203' '1304' '1210'
 '1407' '1403' '1602' '1406' '0208' '0301' '1711' '1702' '1703' '0707'
 '0705' '0404' '0507' '1405' '1018' '1008']

In [12]:
print(f"The dam removals are in {len(huc4s)} HUC4 watersheds. There are 245 HUC4 watersheds in the US (https://nas.er.usgs.gov/hucs.aspx)")

The dam removals are in 156 HUC4 watersheds. There are 245 HUC4 watersheds in the US (https://nas.er.usgs.gov/hucs.aspx)

## Write huc4s to text file to aid stream downloads

In [18]:
with open("../data/processed/huc4_list.txt", "w") as f:
    f.write("\n".join(huc4s))
print("Success!")

Success!

In [20]:
# Confirm file contents are correct
from pathlib import Path

huc4_file = Path("../data/processed/huc4_list.txt")
huc4s = [
    x.strip()
    for x in huc4_file.read_text().splitlines()
    if x.strip()
]

print(len(huc4s))

156